name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "startsWith(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec tsc
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish-npm:
    if: "startsWith(github.event.head_commit.message, 'release')"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
